### ISSUE TITLE
Doppelte Benachrichtungen

### ISSUE THREAD

**Issue by tklein1801** [tklein1801/D2PB#18]
Ich werde in den nächsten Tagen das Problem intensiv beobachten und das ganze so stark zu loggen wie es geht.
Ich habe aktuell die Vermutung dass wenn ein Beitrag bearbeitet wird dieser eventuell wieder oben auf der Liste der Artikel auftaucht und somit die doppelten Benachrichtigungen triggert.
Technisch von Seiten des Bots gibt es aktuell keine Fehler.

```
[LOG:2022-11-05T09:35:23.675Z] (setup) ZensaydotaBot is running development-environment!
[LOG:2022-11-05T09:35:23.852Z] (setup) Updated activity!
[INFORMATION:2022-11-05T09:35:24.390Z] (setup) Starting automated setup...
[ERROR:2022-11-05T09:35:24.523Z] (setup) {"stack":"Error: Bot 'ZensaydotaBot' doesn't have the permissions to manage roles on guild 'La marmota de Bernardo'\n    at createRoles (/usr/src/d2pb/dist/src/core/setup.js:17:19)\n    at guildRoleAndChannelSetup (/usr/src/d2pb/dist/src/core/setup.js:63:9)\n    at /usr/src/d2pb/dist/src/listener/ready.listener.js:116:112\n    at _Collection.forEach (<anonymous>)\n    at /usr/src/d2pb/dist/src/listener/ready.listener.js:116:41\n    at step (/usr/src/d2pb/dist/src/listener/ready.listener.js:33:23)\n    at Object.next (/usr/src/d2pb/dist/src/listener/ready.listener.js:14:53)\n    at fulfilled (/usr/src/d2pb/dist/src/listener/ready.listener.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Bot 'ZensaydotaBot' doesn't have the permissions to manage roles on guild 'La marmota de Bernardo'"}
[ERROR:2022-11-05T09:35:24.524Z] (setup) {"stack":"Error: Bot 'ZensaydotaBot' doesn't have the permissions to manage channels on guild 'La marmota de Bernardo'\n    at createChannels (/usr/src/d2pb/dist/src/core/setup.js:46:19)\n    at guildRoleAndChannelSetup (/usr/src/d2pb/dist/src/core/setup.js:64:9)\n    at /usr/src/d2pb/dist/src/listener/ready.listener.js:116:112\n    at _Collection.forEach (<anonymous>)\n    at /usr/src/d2pb/dist/src/listener/ready.listener.js:116:41\n    at step (/usr/src/d2pb/dist/src/listener/ready.listener.js:33:23)\n    at Object.next (/usr/src/d2pb/dist/src/listener/ready.listener.js:14:53)\n    at fulfilled (/usr/src/d2pb/dist/src/listener/ready.listener.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Bot 'ZensaydotaBot' doesn't have the permissions to manage channels on guild 'La marmota de Bernardo'"}
[ERROR:2022-11-05T09:35:24.525Z] (setup) {"stack":"Error: Bot 'ZensaydotaBot' doesn't have the permissions to manage roles on guild 'Send Help'\n    at createRoles (/usr/src/d2pb/dist/src/core/setup.js:17:19)\n    at guildRoleAndChannelSetup (/usr/src/d2pb/dist/src/core/setup.js:63:9)\n    at /usr/src/d2pb/dist/src/listener/ready.listener.js:116:112\n    at _Collection.forEach (<anonymous>)\n    at /usr/src/d2pb/dist/src/listener/ready.listener.js:116:41\n    at step (/usr/src/d2pb/dist/src/listener/ready.listener.js:33:23)\n    at Object.next (/usr/src/d2pb/dist/src/listener/ready.listener.js:14:53)\n    at fulfilled (/usr/src/d2pb/dist/src/listener/ready.listener.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Bot 'ZensaydotaBot' doesn't have the permissions to manage roles on guild 'Send Help'"}
[ERROR:2022-11-05T09:35:24.526Z] (setup) {"stack":"Error: Bot 'ZensaydotaBot' doesn't have the permissions to manage channels on guild 'Send Help'\n    at createChannels (/usr/src/d2pb/dist/src/core/setup.js:46:19)\n    at guildRoleAndChannelSetup (/usr/src/d2pb/dist/src/core/setup.js:64:9)\n    at /usr/src/d2pb/dist/src/listener/ready.listener.js:116:112\n    at _Collection.forEach (<anonymous>)\n    at /usr/src/d2pb/dist/src/listener/ready.listener.js:116:41\n    at step (/usr/src/d2pb/dist/src/listener/ready.listener.js:33:23)\n    at Object.next (/usr/src/d2pb/dist/src/listener/ready.listener.js:14:53)\n    at fulfilled (/usr/src/d2pb/dist/src/listener/ready.listener.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Bot 'ZensaydotaBot' doesn't have the permissions to manage channels on guild 'Send Help'"}
[LOG:2022-11-05T09:35:24.878Z] (setup) Slash-Commands registered
[LOG:2022-11-05T09:36:52.831Z] (command) {"message":"Member 'Thorben#4051' executed the 'stats'-command on guild 'DulliAG'"}
[ERROR:2022-11-05T11:00:00.255Z] (dota-patch) {"stack":"TypeError: Cannot read properties of null (reading 'patches')\n    at /usr/src/d2pb/dist/src/service/dota.service.js:17:35\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Cannot read properties of null (reading 'patches')"}
[ERROR:2022-11-08T03:10:00.075Z] (dota-patch) {"stack":"FetchError: invalid json response body at https://www.dota2.com/datafeed/patchnoteslist?language=function%20()%20%7B%20%20%20%20%20%20%20%20var%20_this%20=%20this;%20%20%20%20%20%20%20%20return%20new%20Promise(function%20(res,%20rej)%20%7B%20%20%20%20%20%20%20%20%20%20%20%20_this.getPatchNoteList()%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.then(function%20(list)%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20latest%20=%20list.patches[list.patches.length%20-%201];%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(latest%20===%20null)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20rej(new%20Error(%22Couldn%27t%20retrieve%20the%20latest%20patch%22));%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20(0,%20node_fetch_1[%22default%22])(%22https://www.dota2.com/datafeed/patchnotes?version=%22.concat(latest%20===%20null%20%7C%7C%20latest%20===%20void%200%20?%20void%200%20:%20latest.patch_number,%20%22&language=%22).concat(_this.language))%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.then(function%20(response)%20%7B%20return%20response.json();%20%7D)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.then(function%20(json)%20%7B%20return%20res(json);%20%7D)[%22catch%22](function%20(err)%20%7B%20return%20rej(err);%20%7D);%20%20%20%20%20%20%20%20%20%20%20%20%7D)[%22catch%22](function%20(err)%20%7B%20return%20rej(err);%20%7D);%20%20%20%20%20%20%20%20%7D);%20%20%20%20%7D reason: Unexpected token '<', \"<html>\r\n<h\"... is not valid JSON\n    at /usr/src/d2pb/node_modules/node-fetch/lib/index.js:273:32\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"invalid json response body at https://www.dota2.com/datafeed/patchnoteslist?language=function%20()%20%7B%20%20%20%20%20%20%20%20var%20_this%20=%20this;%20%20%20%20%20%20%20%20return%20new%20Promise(function%20(res,%20rej)%20%7B%20%20%20%20%20%20%20%20%20%20%20%20_this.getPatchNoteList()%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.then(function%20(list)%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20var%20latest%20=%20list.patches[list.patches.length%20-%201];%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20(latest%20===%20null)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20rej(new%20Error(%22Couldn%27t%20retrieve%20the%20latest%20patch%22));%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20(0,%20node_fetch_1[%22default%22])(%22https://www.dota2.com/datafeed/patchnotes?version=%22.concat(latest%20===%20null%20%7C%7C%20latest%20===%20void%200%20?%20void%200%20:%20latest.patch_number,%20%22&language=%22).concat(_this.language))%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.then(function%20(response)%20%7B%20return%20response.json();%20%7D)%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.then(function%20(json)%20%7B%20return%20res(json);%20%7D)[%22catch%22](function%20(err)%20%7B%20return%20rej(err);%20%7D);%20%20%20%20%20%20%20%20%20%20%20%20%7D)[%22catch%22](function%20(err)%20%7B%20return%20rej(err);%20%7D);%20%20%20%20%20%20%20%20%7D);%20%20%20%20%7D reason: Unexpected token '<', \"<html>\r\n<h\"... is not valid JSON"}
[ERROR:2022-11-08T03:55:00.319Z] (dota-patch) {"stack":"TypeError: Cannot read properties of null (reading 'patches')\n    at /usr/src/d2pb/dist/src/service/dota.service.js:17:35\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Cannot read properties of null (reading 'patches')"}
[ERROR:2022-11-08T18:05:30.234Z] (dota-patch) {"stack":"TypeError: Cannot read properties of null (reading 'patches')\n    at /usr/src/d2pb/dist/src/service/dota.service.js:17:35\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Cannot read properties of null (reading 'patches')"}
[LOG:2022-11-08T18:40:16.643Z] (command) {"message":"Member 'Thorben#4051' executed the 'stats'-command on guild 'DulliAG'"}
[LOG:2022-11-08T22:05:00.697Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild GTFO INC.","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"GTFO INC."}
[LOG:2022-11-08T22:05:00.721Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild DulliAG","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"DulliAG"}
[LOG:2022-11-08T22:05:00.804Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild UBER's Padded Cell","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"UBER's Padded Cell"}
[LOG:2022-11-08T22:05:00.805Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Server von Thorben","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Server von Thorben"}
[LOG:2022-11-08T22:05:00.813Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Send Help","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Send Help"}
[LOG:2022-11-08T22:05:01.044Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Flame Server","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Flame Server"}
[LOG:2022-11-08T22:05:01.046Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Peace Villa","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Peace Villa"}
[LOG:2022-11-08T22:05:01.047Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Late Game Heroics","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Late Game Heroics"}
[LOG:2022-11-08T22:05:01.307Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Domo's Place","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Domo's Place"}
[LOG:2022-11-08T22:05:01.310Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild 💈BJ's Barber's💈","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"💈BJ's Barber's💈"}
[LOG:2022-11-08T22:05:01.310Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Pros united","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Pros united"}
[LOG:2022-11-08T22:05:01.311Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Steamroll","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Steamroll"}
[LOG:2022-11-08T22:05:01.513Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild DS.Revolution","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"DS.Revolution"}
[LOG:2022-11-08T22:05:01.538Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild prokiemers🍎","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"prokiemers🍎"}
[LOG:2022-11-08T22:05:02.200Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Church Of The Unholy","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Church Of The Unholy"}
[LOG:2022-11-08T22:05:03.985Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Zensay´s","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Zensay´s"}
[LOG:2022-11-08T22:10:00.324Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild DulliAG","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"DulliAG"}
[LOG:2022-11-08T22:10:00.332Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Server von Thorben","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Server von Thorben"}
[LOG:2022-11-08T22:10:00.339Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild UBER's Padded Cell","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"UBER's Padded Cell"}
[LOG:2022-11-08T22:10:00.345Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild GTFO INC.","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"GTFO INC."}
[LOG:2022-11-08T22:10:00.496Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild 💈BJ's Barber's💈","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"💈BJ's Barber's💈"}
[LOG:2022-11-08T22:10:00.497Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild prokiemers🍎","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"prokiemers🍎"}
[LOG:2022-11-08T22:10:00.498Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Zensay´s","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Zensay´s"}
[LOG:2022-11-08T22:10:00.498Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Steamroll","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Steamroll"}
[LOG:2022-11-08T22:10:00.499Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Domo's Place","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Domo's Place"}
[LOG:2022-11-08T22:10:00.566Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Pros united","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Pros united"}
[LOG:2022-11-08T22:10:00.635Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Peace Villa","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Peace Villa"}
[LOG:2022-11-08T22:10:00.635Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Late Game Heroics","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Late Game Heroics"}
[LOG:2022-11-08T22:10:00.636Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild DS.Revolution","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"DS.Revolution"}
[LOG:2022-11-08T22:10:00.636Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Send Help","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Send Help"}
[LOG:2022-11-08T22:10:00.636Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Church Of The Unholy","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Church Of The Unholy"}
[LOG:2022-11-08T22:10:01.019Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Flame Server","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Flame Server"}
[LOG:2022-11-08T22:20:00.352Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Church Of The Unholy","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Church Of The Unholy"}
[LOG:2022-11-08T22:20:00.352Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild DS.Revolution","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"DS.Revolution"}
[LOG:2022-11-08T22:20:00.360Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Late Game Heroics","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Late Game Heroics"}
[LOG:2022-11-08T22:20:00.377Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Server von Thorben","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Server von Thorben"}
[LOG:2022-11-08T22:20:00.614Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild GTFO INC.","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"GTFO INC."}
[LOG:2022-11-08T22:20:00.615Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild prokiemers🍎","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"prokiemers🍎"}
[LOG:2022-11-08T22:20:00.615Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Domo's Place","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Domo's Place"}
[LOG:2022-11-08T22:20:00.615Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild 💈BJ's Barber's💈","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"💈BJ's Barber's💈"}
[LOG:2022-11-08T22:20:00.616Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Peace Villa","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Peace Villa"}
[LOG:2022-11-08T22:20:00.617Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Pros united","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Pros united"}
[LOG:2022-11-08T22:20:00.617Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Steamroll","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Steamroll"}
[LOG:2022-11-08T22:20:00.617Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild UBER's Padded Cell","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"UBER's Padded Cell"}
[LOG:2022-11-08T22:20:00.618Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Flame Server","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Flame Server"}
[LOG:2022-11-08T22:20:00.618Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild DulliAG","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"DulliAG"}
[LOG:2022-11-08T22:20:00.982Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Send Help","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Send Help"}
[LOG:2022-11-08T22:20:01.365Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Zensay´s","article":"4732747437221509206","date":"2022-11-08T22:03:46.000Z","guild":"Zensay´s"}
[LOG:2022-11-08T22:25:00.330Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild 💈BJ's Barber's💈","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"💈BJ's Barber's💈"}
[LOG:2022-11-08T22:25:00.333Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Peace Villa","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Peace Villa"}
[LOG:2022-11-08T22:25:00.334Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild UBER's Padded Cell","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"UBER's Padded Cell"}
[LOG:2022-11-08T22:25:00.334Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild DulliAG","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"DulliAG"}
[LOG:2022-11-08T22:25:00.340Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild DS.Revolution","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"DS.Revolution"}
[LOG:2022-11-08T22:25:00.511Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Church Of The Unholy","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Church Of The Unholy"}
[LOG:2022-11-08T22:25:00.515Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Zensay´s","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Zensay´s"}
[LOG:2022-11-08T22:25:00.515Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Send Help","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Send Help"}
[LOG:2022-11-08T22:25:00.516Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Steamroll","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Steamroll"}
[LOG:2022-11-08T22:25:00.516Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Server von Thorben","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Server von Thorben"}
[LOG:2022-11-08T22:25:00.660Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Pros united","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Pros united"}
[LOG:2022-11-08T22:25:00.661Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild GTFO INC.","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"GTFO INC."}
[LOG:2022-11-08T22:25:00.661Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild prokiemers🍎","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"prokiemers🍎"}
[LOG:2022-11-08T22:25:00.662Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Late Game Heroics","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Late Game Heroics"}
[LOG:2022-11-08T22:25:00.735Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Domo's Place","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Domo's Place"}
[LOG:2022-11-08T22:25:00.736Z] (dota-news) {"message":"Steam news notification for Dota 2 was sent to the guild Flame Server","article":"4732747437206574603","date":"2022-11-04T19:37:13.000Z","guild":"Flame Server"}
npm ERR! path /usr/src/d2pb
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh -c -- node dist/src/index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-05T09_35_22_079Z-debug-0.log
```

**Comment by tklein1801** [comment]
@Z3nsay seit meiner Fehlersuche ist es nicht mehr vorgekommen, dass mehrere Beiträge an einem Tag veröffentlich wurden, wodurch sich das ganze natürlich auch nicht loggen lässt.

Ich habe ja um diese doppelten Benachrichtigungen vorzubeugen diese auf allen Servern außer meinem abgestellt damit keiner  mehr damit belästigt und falsch informiert wird. Da sich der Prozess wie wir gerade merken etwas in die Länge zieht, kann ich die Benachrichtigungen auch wieder für alle Server aktivieren wenn du möchtest.

[public_logs_export_2022-11-18_155658.csv](https://github.com/DulliAG/D2PB/files/10042287/public_logs_export_2022-11-18_155658.csv)

**Comment by Z3nsay** [comment]
Könntest du vielleicht sonst bei „news“ nur die „Community Announcements“ durchlassen und die anderen nur auf deinem Server loggen? Mit freundlichen GrüßenErdinc Akay Von: ThorbenGesendet: Freitag, 18. November 2022 15:58An: DulliAG/D2PBCc: Z3nsay; MentionBetreff: Re: [DulliAG/D2PB] Doppelte Benachrichtungen (Issue ***@***.*** seit meiner Fehlersuche ist es nicht mehr vorgekommen, dass mehrere Beiträge an einem Tag veröffentlich wurden, wodurch sich das ganze natürlich auch nicht loggen lässt.Ich habe ja um diese doppelten Benachrichtigungen vorzubeugen diese auf allen Servern außer meinem abgestellt damit keiner mehr damit belästigt und falsch informiert wird. Da sich der Prozess wie wir gerade merken etwas in die Länge zieht, kann ich die Benachrichtigungen auch wieder für alle Server aktivieren wenn du möchtest.public_logs_export_2022-11-18_155658.csv—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by tklein1801** [comment]
Moin, es ist endlich soweit gestern Abend trat der Fehler erneut auf. Ich werde  die Logs herunterladen und mir das ganze anschauen und hoffe den Fehler darin erfasst zu haben.
Mit dem nächsten Update wird noch eine lokale Datenbank mittels Docker angebunden, um Crashs beim beschreiben der Daten vorzubeugen.

**Comment by tklein1801** [comment]
Wird erstmal  geschlossen,  da das Problem seither nicht mehr aufgetreten ist und seit Anbindung an die Datenbank seit Version v2.0.11 auch nicht mehr auftreten sollten.
